<a href="https://colab.research.google.com/github/umanari145/python_ai/blob/main/kikagaku01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [2]:
y = np.array([2,3.9,6.1])
y

array([2. , 3.9, 6.1])

# データの中心化

In [14]:
# 平均の算出
x.mean()


2.0

In [15]:
#中心化

xc = x-x.mean()
xc

array([-1.,  0.,  1.])

In [16]:
yc = y-y.mean()
yc

array([-2. , -0.1,  2.1])

## パラメータaの計算

In [17]:
# 要素ごとの掛け算 要素
xx=xc*xc
xx

array([1., 0., 1.])

In [20]:
xy = xc*yc
xy

array([ 2. , -0. ,  2.1])

In [23]:
xy.sum()

a = xy.sum()/xx.sum()
a

2.05

# 新しいセクション

In [27]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/kikagaku_sample.csv')


FileNotFoundError: ignored